# Your Name or Company
title: Kevin Krotzer
email: kevin@kevinkrotzer.com
url: 'http://kevinkrotzer.com'
baseurl:  #if necessary, use format '/baseurl' without trailing slash

# Description of your website. This is used for social sharing.
description:  This is something about Kevin.

# A brief blurb about yourself
content: Nullam id dolor id nibh ultricies vehicula ut id elit. Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mattis consectetur purus sit amet fermentum.

# A picture of yourself
avatar: /assets/img/profile.png

# Add your social links
social:
  - platform: facebook
    url: https://www.facebook.com/kevinkrotzer
    icon: fa-brands fa-facebook-f
  - platform: linkedin
    url: https://www.linkedin.com/in/kevinkrotzer
    icon: fa-brands fa-linkedin-in
  - platform: twitter
    url: https://www.twitter.com/kevinkrotzer
    icon: fa-brands fa-twitter
  - platform: project
    url: https://www.crackedasphalt.com
    icon: fa-solid fa-mountain-city

# Contact Page Info
contact:
  enable: true
  url: /contact/
  icon: fa-solid fa-envelope

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "G-ZYEBZGF9HT" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center


#sass
sass:
  sass_dir:           _sass
  style:              compressed