# Site settings
title: Kevin Krotzer
description: 'hello world'
url: 'http://kevinkrotzer.com'
baseurl: '/'
google_analytics: 'UA-82095106-1'
disqus_shortname: 'kevinkrotzer-com'

author:
  name: 'Kevin Krotzer'
  email: kevin@kevinkrotzer.com
  city: San Francisco
  state: CA
  country: USA
  twitter_username: kevinkrotzer
  facebook_username: kevinkrotzer
  github_username:  
  linkedin_username:  kevinkrotzer
  googleplus_username: 
  instagram_username: 
  pinterest_username: 
  reddit_username: 
  vimeo_username: 
  yelp_username: 
  youtube_username: 

humans:
  standards: HTML5, CSS3
  components: Jekyll
  software: Notepad ++, GIMP
  

thanks:
  background_title: 'Sierra' #required for background credit to appear in footer and in humans.txt/thanks
  background_photographer: 'Greg Duncan' #required for background credit to appear in footer
  background_photographer_contact:  #optional
  theme_title: 'jekyll-uno' #optional
  theme_developer: 'Josh Gerdes' #required for name to appear in humans.txt/thanks
  theme_developer_contact: 'https://github.com/joshgerdes' #required for contact to appear in humans.txt/thanks
  
prose:
  rooturl: '_posts'
  siteurl: 'http://kevinkrotzer.com'
  media: 'images/posts'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "text"
          label: "[category1,category2]"
      - name: "tags"
        field:
          element: "text"
          label: "[tag1,tag2]"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
