# Site settings
title: Kevin Krotzer
description: 'Test'
url: 'http://kevinkrotzer.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Kevin Krotzer'
  email: kevin@kevinkrotzer.com
  twitter_username: kevinkrotzer
  facebook_username: kevinkrotzer
  github_username:  
  linkedin_username:  kevinkrotzer

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
