# Site settings
title: Kevin Krotzer
description: 'hello world'
url: 'http://kevinkrotzer.com'
baseurl: '/'
google_analytics: 'UA-82095106-1'
disqus_shortname: 'kevinkrotzer-com'

author:
  name: 'Kevin Krotzer'
  email: kevin@kevinkrotzer.com
  twitter_username: kevinkrotzer
  facebook_username: kevinkrotzer
  github_username:  
  linkedin_username:  kevinkrotzer
  googleplus_username: 
  instagram_username: 
  pinterest_username: 
  reddit_username: 
  vimeo_username: 
  yelp_username: 
  youtube_username: 
  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
